project:
  type: website

website:
  title: "Michael Kerr"
  search: false
  page-footer: "Copyright 2026, Michael Kerr"
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cv.qmd

format:
  html:
    theme:
      - Cosmo
    css: styles.css
    toc: true
    include-after-body: nav-overlay.html

execute:
  freeze: auto



