project:
  type: website

website:
  title: "Michael Kerr"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cv.qmd

format:
  html:
    theme:
      - Cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



